### PR TITLE
Add pretty_print argument to TutkainEvaluateCommand.

### PR DESCRIPTION
**Pull request by dmitrydprog**
@eerohele  What do you thing? It's may useful feature?

### CODE REVIEW

**Comment by dmitrydprog** [comment]
Screenshot 2021-07-26 at 16 29 43

**Comment by dmitrydprog** [comment]
But this code have one problem, long lines do not wrap on next line, and i don’t  find way to fix it. Minihtml (sublime use it for display phantom blocks) doesn’t have the right css class.

It’s no problem for me, but for other people can be.

If anyone known how to fix the problem, answer me please.

**Comment by eerohele** [comment]
I'll need to try this out, but my initial feeling is that this would be a useful feature, although I don't use inline results a lot myself.

>But this code have one problem, long lines do not wrap on next line, and i don’t find way to fix it.

The only solution I can think of is to insert `<br>` elements manually at the word wrap column, but I'm not sure how well that would work.

I'll try this out when I get the chance and get back to you.

**Comment by dmitrydprog** [comment]
Ye, i may use python for break line, but it's looks like workaround.
If minithml had supported pre tag or css directives to break word it would have been better.

> I'll try this out when I get the chance and get back to you.

Let's me try, don't waste your time.

**Comment by eerohele** [comment]
>Ye, i may use python for break line, but it's looks like workaround.
>If minithml had supported pre tag or css directives to break word it would have been better.

Yeah, it's a hack for sure. I [use it as a workaround for doc popups, too](https://github.com/eerohele/Tutkain/blob/a5bb79f11d968d2bf9e66b39e2adbba95bd0404d/src/repl/info.py#L65-L69).

>Let's me try, don't waste your time.

Cool, thanks! One thing, though, is that I'm not sure whether it is useful to make this optional. If we can figure out a way to pretty-print inline results well enough, we should probably just make that the default behavior. In other words, I think we could drop the `pretty_print` parameter. Or, if we choose to keep it, we should probably rename it to something like `pretty_print_inline_result` to avoid ambiguity.

**Comment by dmitrydprog** [comment]
I would like stay this parameter is optional and disabled by default.
Very long result may force users scrolls many lines.

Good news, i found solution for break lines. Just replace only leading spaces.

If code is ok, then i squash commits.

Example break lines:

Screenshot 2021-07-29 at 11 19 00

**Comment by eerohele** [comment]
Looking pretty good! A couple of more things:

I think I'd prefer it if the result began on the same line as the `=>` and the subsequent lines were aligned accordingly. Furthermore, I'd prefer to remove the margin on the `<p>` element.

Something along these lines:

```diff
diff --git a/src/inline.py b/src/inline.py
index 9203250..c0c3ed5 100644
--- a/src/inline.py
+++ b/src/inline.py
@@ -5,19 +5,19 @@ import html
 
 def show(view, point, value, pretty_print_inline_result=False):
     layout = sublime.LAYOUT_INLINE
-    value = "<br/>" + html.escape(value)
+    value = html.escape(value)
 
     if pretty_print_inline_result:
         value = re.sub(
             r"(?m)^(\s+)",
-            lambda s: "&nbsp;" * (s.span()[1] - s.span()[0]),
+            lambda s: "&nbsp;&nbsp;&nbsp;&nbsp;" * (s.span()[1] - s.span()[0]),
             value
         ).replace("\n", "<br/>")
 
         layout = sublime.LAYOUT_BLOCK
 
     style = "color: color(var(--foreground) alpha(0.5));"
-    html_text = """<p><span style="{}">=></span> {}</p>""".format(style, value)
+    html_text = """<p style="margin: 0;"><span style="{}">=></span> {}</p>""".format(style, value)
     region = sublime.Region(point, point)
     view.add_phantom("tutkain/eval", region, html_text, layout)
```

Can you try that out and see whether it works for you?

One more thing: sorry to go back and forth on this, but I think I would actually prefer to have `inline_result: "block"` instead of a separate parameter. `inline_result: true` would be the same as `inline`. Sound good to you?

**Comment by dmitrydprog** [comment]
> Can you try that out and see whether it works for you?
Okey, on this weekend i try.

> Sound good to you?
Ye, it's good.

**Comment by dmitrydprog** [comment]
> lambda s: "&nbsp;&nbsp;&nbsp;&nbsp;" * (s.span()[1] - s.span()[0]),

Why four nbsp?

4 nbsp:
Screenshot 2021-07-30 at 17 16 24

2 nbsp:
Screenshot 2021-07-30 at 17 16 50

1 nbsp:
Screenshot 2021-07-30 at 17 21 01

I think, that we should't change space count, because we receive preformatted text with right amount space. Otherwise we broken right indentation.
Case with one nbsp looks good, what do you think?

**Comment by eerohele** [comment]
Oh yeah, forgot to consider nested data structures...

I think we could do [something like this to get everything to line up nicely](https://github.com/eerohele/Tutkain/blob/a5bb79f11d968d2bf9e66b39e2adbba95bd0404d/src/repl/client.py#L157-L168).

Here's a very quick stab at it that's not pretty at all but maybe illustrates what I mean:

```diff
diff --git a/src/inline.py b/src/inline.py
index 9203250..d4e083f 100644
--- a/src/inline.py
+++ b/src/inline.py
@@ -1,23 +1,35 @@
+from inspect import cleandoc
 import sublime
 import re
 import html
 
 
+def format(form):
+    if lines := cleandoc(form).splitlines():
+        first_line = lines[0] + "\n"
+        next_lines = "\n".join(map(lambda line: (2 * "&nbsp;") + line, lines[1:]))
+
+        if next_lines:
+            next_lines += "\n"
+
+        return f"""{first_line}{next_lines}"""
+
+
 def show(view, point, value, pretty_print_inline_result=False):
     layout = sublime.LAYOUT_INLINE
-    value = "<br/>" + html.escape(value)
+    value = html.escape(value)
 
     if pretty_print_inline_result:
-        value = re.sub(
+        value = format(re.sub(
             r"(?m)^(\s+)",
             lambda s: "&nbsp;" * (s.span()[1] - s.span()[0]),
             value
-        ).replace("\n", "<br/>")
+        )).replace("\n", "<br/>")
 
         layout = sublime.LAYOUT_BLOCK
 
     style = "color: color(var(--foreground) alpha(0.5));"
-    html_text = """<p><span style="{}">=></span> {}</p>""".format(style, value)
+    html_text = """<p style="margin: 0"><span style="{}">=></span> {}</p>""".format(style, value)
     region = sublime.Region(point, point)
     view.add_phantom("tutkain/eval", region, html_text, layout)
 ```

That's ugly,

**Comment by dmitrydprog** [comment]
@eerohele thanks for code, now it looks good.
Screenshot 2021-07-31 at 17 10 29

**Comment by eerohele** [comment]
Thanks, looks good! If you can squash this into a single commit, I think it's ready for merging.

**Pull request merged**
